version: '3'
services:
  nginx:
    image: nginx
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./nginx/conf.d:/etc/nginx/conf.d
     - ./nginx/html:/usr/share/nginx/html
    ports:
     - "80:80"
    depends_on:
     - "zafira"
     - "jenkins-master"
#     - "selenium-hub"
    restart: always
  db:
    image: qaprosoft/postgres:9.6
    volumes:
     - ./pgdata:/var/lib/postgresql/data
     - ./database:/docker-entrypoint-initdb.d
    ports:
     - "5432:5432"
    env_file:
     - variables.env
    restart: always
  zafira:
    image: qaprosoft/zafira
    env_file:
     - variables.env
    #keep only for debugging purposes
    ports:
     - "8001:8001"
    depends_on:
     - "db"
    restart: always
  jenkins-master:
    image: qaprosoft/jenkins-master
    env_file:
     - variables.env
    volumes:
     - ./jenkins:/var/jenkins_home
     - $HOME/.ssh:/var/jenkins_home/.ssh
     - $HOME/.m2:/var/jenkins_home/.m2
    ports:
     - "50000:50000"
    restart: always
  jenkins-slave:
    image: qaprosoft/jenkins-slave
    env_file:
     - variables.env
    volumes:
     - $HOME/.ssh:/root/.ssh
     - $HOME/.m2:/root/.m2
    ports:
     - "50001:50000"
    depends_on:
     - "jenkins-master"
    restart: always
#  selenium-hub:
#    image: qaprosoft/selenium-hub
#    env_file:
#     - variables.env
#    ports:
#     - "4444:4444"
#    restart: always
  sonarqube:
    image: qaprosoft/sonarqube
    env_file:
     - variables.env
    command: -Dsonar.web.context=/sonarqube
    depends_on:
     - "db"
    restart: always
  rabbitmq:
    image: qaprosoft/rabbitmq
    env_file:
     - variables.env
    ports:
     - 15672:15672
     - 15674:15674
     - 5672:5672
    restart: always
#  chrome:
#    image: selenium/node-chrome
#    environment:
#    - HUB_HOST=selenium-hub
#    - NODE_MAX_INSTANCES=5
#    - NODE_MAX_SESSION=5
#    volumes:
#    - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952
#    depends_on:
#     - "selenium-hub"
#  firefox:
#    image: selenium/node-firefox
#    environment:
#    - HUB_HOST=selenium-hub
#    - NODE_MAX_INSTANCES=5
#    - NODE_MAX_SESSION=5
#    depends_on:
#     - "selenium-hub"
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    volumes:
     - "./selenoid:/etc/selenoid"
     - "/var/run/docker.sock:/var/run/docker.sock"
     - "./selenoid/video:/opt/selenoid/video"
    environment:
     - OVERRIDE_VIDEO_OUTPUT_DIR=./selenoid/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video"]
    ports:
     - "4444:4444"
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
     - selenoid
    ports:
     - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
    depends_on:
     - selenoid

